package me.hapyl.scavenger.task;

import com.google.common.collect.Lists;
import com.google.common.collect.Maps;
import com.google.common.collect.Sets;
import me.hapyl.spigotutils.module.util.CollectionUtils;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.advancement.Advancement;
import org.bukkit.entity.Breedable;
import org.bukkit.entity.Entity;
import org.bukkit.entity.EntityType;
import org.bukkit.event.entity.EntityDamageEvent;

import java.lang.reflect.Field;
import java.util.List;
import java.util.Map;
import java.util.Set;

import static org.bukkit.event.entity.EntityDamageEvent.DamageCause.values;

public class Type<T> {

    public static final Type<Material> CRAFT_ITEM = new Type<>("Crafter");
    public static final Type<Material> GATHER_ITEM = new Type<>("Gatherer");
    public static final Type<EntityType> KILL_ENTITY = new Type<>("Slayer");
    public static final Type<EntityType> BREED_ANIMAL = new Type<>("Farmer");
    public static final Type<EntityDamageEvent.DamageCause> DIE_FROM_CAUSE = new Type<>("Death");
    public static final Type<EntityType> DIE_FROM_ENTITY = new Type<>("Victim");
    public static final Type<Advancement> ADVANCEMENT_ADVANCER = new Type<>("Advancer");

    public static List<Type<?>> values;
    public static Map<String, Type<?>> byName;

    static {

        values = Lists.newArrayList();
        byName = Maps.newHashMap();
        for (Field field : Type.class.getFields()) {
            try {
                final Object obj = field.get(null);
                if (obj instanceof Type<?> t) {
                    byName.put(field.getName(), t);
                    values.add(t);
                }
            } catch (IllegalAccessException ignored) {
            }
        }

        // Material related
        for (Material material : Material.values()) {
            // Gather item
            if (material.isItem()) {
                final String materialName = material.name();
                // TODO: 012. 12/09/2022 - Validate items
                if (!stringContainsAny(materialName, "SPAWN_EGG", "COMMAND_BLOCK")) {
                    GATHER_ITEM.addAllowed(material);
                }
            }

            // Craftable
            if (isUsedInRecipe(material)) {
                switch (material) {
                    case CRAFTING_TABLE -> {
                    }
                    default -> CRAFT_ITEM.addAllowed(material);
                }
            }
        }

        // Entity related
        for (EntityType value : EntityType.values()) {
            if (value.isAlive()) {
                switch (value) {
                    case PLAYER, ENDER_DRAGON, WITHER, SHULKER, ILLUSIONER, ZOMBIE_HORSE, ARMOR_STAND -> {
                    }
                    default -> {
                        KILL_ENTITY.addAllowed(value);

                        // TODO: Validate hostile
                        DIE_FROM_ENTITY.addAllowed(value);
                    }
                }
            }

            final Class<? extends Entity> entityClass = value.getEntityClass();
            if (entityClass != null && Breedable.class.isAssignableFrom(entityClass)) {
                switch (value) {
                    case SKELETON_HORSE, ZOMBIE_HORSE, MUSHROOM_COW, OCELOT, POLAR_BEAR, TRADER_LLAMA, HOGLIN, STRIDER, WANDERING_TRADER, VILLAGER -> {
                    }
                    default -> BREED_ANIMAL.addAllowed(value);
                }
            }
        }

        // Death from cause
        for (EntityDamageEvent.DamageCause cause : values()) {
            switch (cause) {
                case ENTITY_SWEEP_ATTACK, MELTING, VOID, SUICIDE, DRAGON_BREATH, CUSTOM, FLY_INTO_WALL, DRYOUT, BLOCK_EXPLOSION -> {
                }
                default -> DIE_FROM_CAUSE.addAllowed(cause);
            }
        }

        // Advancements
        Bukkit.advancementIterator().forEachRemaining(adv -> {
            // TODO: Validate
            ADVANCEMENT_ADVANCER.addAllowed(adv);
        });

    }

    private final String name;
    private final Set<T> allowed;

    Type(String name) {
        this.name = name;
        this.allowed = Sets.newHashSet();
    }

    @SafeVarargs
    public final void addAllowed(T... t) {
        allowed.addAll(List.of(t));
    }

    public boolean isAllowed(T t) {
        return allowed.contains(t);
    }

    public Set<T> getAllowed() {
        return allowed;
    }

    public T randomAllowed() {
        return CollectionUtils.randomElement(allowed);
    }

    public String getName() {
        return name;
    }

    public String getAccepting() {
        final Object f = allowed.toArray()[0];
        return f == null ? "NULL" : f.getClass().toString();
    }

    private static boolean stringContainsAny(String string, String... other) {
        for (String s : other) {
            if (string.toLowerCase().contains(s.toLowerCase())) {
                return true;
            }
        }
        return false;
    }

    private static boolean isUsedInRecipe(Material material) {
        return switch (material) {
            case GRANITE, POLISHED_GRANITE, DIORITE, POLISHED_DIORITE, ANDESITE, POLISHED_ANDESITE, POLISHED_DEEPSLATE, DRIPSTONE_BLOCK, COARSE_DIRT, OAK_PLANKS, SPRUCE_PLANKS, BIRCH_PLANKS, JUNGLE_PLANKS, ACACIA_PLANKS, DARK_OAK_PLANKS, MANGROVE_PLANKS, CRIMSON_PLANKS, WARPED_PLANKS, COAL_BLOCK, RAW_IRON_BLOCK, RAW_COPPER_BLOCK, RAW_GOLD_BLOCK, AMETHYST_BLOCK, IRON_BLOCK, COPPER_BLOCK, GOLD_BLOCK, DIAMOND_BLOCK, NETHERITE_BLOCK, CUT_COPPER, EXPOSED_CUT_COPPER, WEATHERED_CUT_COPPER, OXIDIZED_CUT_COPPER, CUT_COPPER_STAIRS, EXPOSED_CUT_COPPER_STAIRS, WEATHERED_CUT_COPPER_STAIRS, OXIDIZED_CUT_COPPER_STAIRS, CUT_COPPER_SLAB, EXPOSED_CUT_COPPER_SLAB, WEATHERED_CUT_COPPER_SLAB, OXIDIZED_CUT_COPPER_SLAB, WAXED_COPPER_BLOCK, WAXED_EXPOSED_COPPER, WAXED_WEATHERED_COPPER, WAXED_OXIDIZED_COPPER, WAXED_CUT_COPPER, WAXED_EXPOSED_CUT_COPPER, WAXED_WEATHERED_CUT_COPPER, WAXED_OXIDIZED_CUT_COPPER, WAXED_CUT_COPPER_STAIRS, WAXED_EXPOSED_CUT_COPPER_STAIRS, WAXED_WEATHERED_CUT_COPPER_STAIRS, WAXED_OXIDIZED_CUT_COPPER_STAIRS, WAXED_CUT_COPPER_SLAB, WAXED_EXPOSED_CUT_COPPER_SLAB, WAXED_WEATHERED_CUT_COPPER_SLAB, WAXED_OXIDIZED_CUT_COPPER_SLAB, MUDDY_MANGROVE_ROOTS, STRIPPED_OAK_WOOD, STRIPPED_SPRUCE_WOOD, STRIPPED_BIRCH_WOOD, STRIPPED_JUNGLE_WOOD, STRIPPED_ACACIA_WOOD, STRIPPED_DARK_OAK_WOOD, STRIPPED_MANGROVE_WOOD, STRIPPED_CRIMSON_HYPHAE, STRIPPED_WARPED_HYPHAE, OAK_WOOD, SPRUCE_WOOD, BIRCH_WOOD, JUNGLE_WOOD, ACACIA_WOOD, DARK_OAK_WOOD, MANGROVE_WOOD, CRIMSON_HYPHAE, WARPED_HYPHAE, TINTED_GLASS, LAPIS_BLOCK, SANDSTONE, CHISELED_SANDSTONE, CUT_SANDSTONE, WHITE_WOOL, ORANGE_WOOL, MAGENTA_WOOL, LIGHT_BLUE_WOOL, YELLOW_WOOL, LIME_WOOL, PINK_WOOL, GRAY_WOOL, LIGHT_GRAY_WOOL, CYAN_WOOL, PURPLE_WOOL, BLUE_WOOL, BROWN_WOOL, GREEN_WOOL, RED_WOOL, BLACK_WOOL, MOSS_CARPET, OAK_SLAB, SPRUCE_SLAB, BIRCH_SLAB, JUNGLE_SLAB, ACACIA_SLAB, DARK_OAK_SLAB, MANGROVE_SLAB, CRIMSON_SLAB, WARPED_SLAB, STONE_SLAB, SMOOTH_STONE_SLAB, SANDSTONE_SLAB, CUT_SANDSTONE_SLAB, COBBLESTONE_SLAB, BRICK_SLAB, STONE_BRICK_SLAB, MUD_BRICK_SLAB, NETHER_BRICK_SLAB, QUARTZ_SLAB, RED_SANDSTONE_SLAB, CUT_RED_SANDSTONE_SLAB, PURPUR_SLAB, PRISMARINE_SLAB, PRISMARINE_BRICK_SLAB, DARK_PRISMARINE_SLAB, BRICKS, BOOKSHELF, MOSSY_COBBLESTONE, TORCH, END_ROD, PURPUR_BLOCK, PURPUR_PILLAR, PURPUR_STAIRS, CHEST, CRAFTING_TABLE, FURNACE, LADDER, COBBLESTONE_STAIRS, SNOW, SNOW_BLOCK, CLAY, JUKEBOX, OAK_FENCE, SPRUCE_FENCE, BIRCH_FENCE, JUNGLE_FENCE, ACACIA_FENCE, DARK_OAK_FENCE, MANGROVE_FENCE, CRIMSON_FENCE, WARPED_FENCE, JACK_O_LANTERN, POLISHED_BASALT, SOUL_TORCH, GLOWSTONE, STONE_BRICKS, MOSSY_STONE_BRICKS, CHISELED_STONE_BRICKS, PACKED_MUD, MUD_BRICKS, DEEPSLATE_BRICKS, DEEPSLATE_TILES, CHISELED_DEEPSLATE, IRON_BARS, CHAIN, GLASS_PANE, MELON, BRICK_STAIRS, STONE_BRICK_STAIRS, MUD_BRICK_STAIRS, NETHER_BRICKS, CHISELED_NETHER_BRICKS, NETHER_BRICK_FENCE, NETHER_BRICK_STAIRS, ENCHANTING_TABLE, END_STONE_BRICKS, SANDSTONE_STAIRS, ENDER_CHEST, EMERALD_BLOCK, OAK_STAIRS, SPRUCE_STAIRS, BIRCH_STAIRS, JUNGLE_STAIRS, ACACIA_STAIRS, DARK_OAK_STAIRS, MANGROVE_STAIRS, CRIMSON_STAIRS, WARPED_STAIRS, BEACON, COBBLESTONE_WALL, MOSSY_COBBLESTONE_WALL, BRICK_WALL, PRISMARINE_WALL, RED_SANDSTONE_WALL, MOSSY_STONE_BRICK_WALL, GRANITE_WALL, STONE_BRICK_WALL, MUD_BRICK_WALL, NETHER_BRICK_WALL, ANDESITE_WALL, RED_NETHER_BRICK_WALL, SANDSTONE_WALL, END_STONE_BRICK_WALL, DIORITE_WALL, BLACKSTONE_WALL, POLISHED_BLACKSTONE_WALL, POLISHED_BLACKSTONE_BRICK_WALL, COBBLED_DEEPSLATE_WALL, POLISHED_DEEPSLATE_WALL, DEEPSLATE_BRICK_WALL, DEEPSLATE_TILE_WALL, ANVIL, CHISELED_QUARTZ_BLOCK, QUARTZ_BLOCK, QUARTZ_BRICKS, QUARTZ_PILLAR, QUARTZ_STAIRS, WHITE_TERRACOTTA, ORANGE_TERRACOTTA, MAGENTA_TERRACOTTA, LIGHT_BLUE_TERRACOTTA, YELLOW_TERRACOTTA, LIME_TERRACOTTA, PINK_TERRACOTTA, GRAY_TERRACOTTA, LIGHT_GRAY_TERRACOTTA, CYAN_TERRACOTTA, PURPLE_TERRACOTTA, BLUE_TERRACOTTA, BROWN_TERRACOTTA, GREEN_TERRACOTTA, RED_TERRACOTTA, BLACK_TERRACOTTA, HAY_BLOCK, WHITE_CARPET, ORANGE_CARPET, MAGENTA_CARPET, LIGHT_BLUE_CARPET, YELLOW_CARPET, LIME_CARPET, PINK_CARPET, GRAY_CARPET, LIGHT_GRAY_CARPET, CYAN_CARPET, PURPLE_CARPET, BLUE_CARPET, BROWN_CARPET, GREEN_CARPET, RED_CARPET, BLACK_CARPET, PACKED_ICE, WHITE_STAINED_GLASS, ORANGE_STAINED_GLASS, MAGENTA_STAINED_GLASS, LIGHT_BLUE_STAINED_GLASS, YELLOW_STAINED_GLASS, LIME_STAINED_GLASS, PINK_STAINED_GLASS, GRAY_STAINED_GLASS, LIGHT_GRAY_STAINED_GLASS, CYAN_STAINED_GLASS, PURPLE_STAINED_GLASS, BLUE_STAINED_GLASS, BROWN_STAINED_GLASS, GREEN_STAINED_GLASS, RED_STAINED_GLASS, BLACK_STAINED_GLASS, WHITE_STAINED_GLASS_PANE, ORANGE_STAINED_GLASS_PANE, MAGENTA_STAINED_GLASS_PANE, LIGHT_BLUE_STAINED_GLASS_PANE, YELLOW_STAINED_GLASS_PANE, LIME_STAINED_GLASS_PANE, PINK_STAINED_GLASS_PANE, GRAY_STAINED_GLASS_PANE, LIGHT_GRAY_STAINED_GLASS_PANE, CYAN_STAINED_GLASS_PANE, PURPLE_STAINED_GLASS_PANE, BLUE_STAINED_GLASS_PANE, BROWN_STAINED_GLASS_PANE, GREEN_STAINED_GLASS_PANE, RED_STAINED_GLASS_PANE, BLACK_STAINED_GLASS_PANE, PRISMARINE, PRISMARINE_BRICKS, DARK_PRISMARINE, PRISMARINE_STAIRS, PRISMARINE_BRICK_STAIRS, DARK_PRISMARINE_STAIRS, SEA_LANTERN, RED_SANDSTONE, CHISELED_RED_SANDSTONE, CUT_RED_SANDSTONE, RED_SANDSTONE_STAIRS, MAGMA_BLOCK, NETHER_WART_BLOCK, RED_NETHER_BRICKS, BONE_BLOCK, SHULKER_BOX, WHITE_CONCRETE_POWDER, ORANGE_CONCRETE_POWDER, MAGENTA_CONCRETE_POWDER, LIGHT_BLUE_CONCRETE_POWDER, YELLOW_CONCRETE_POWDER, LIME_CONCRETE_POWDER, PINK_CONCRETE_POWDER, GRAY_CONCRETE_POWDER, LIGHT_GRAY_CONCRETE_POWDER, CYAN_CONCRETE_POWDER, PURPLE_CONCRETE_POWDER, BLUE_CONCRETE_POWDER, BROWN_CONCRETE_POWDER, GREEN_CONCRETE_POWDER, RED_CONCRETE_POWDER, BLACK_CONCRETE_POWDER, BLUE_ICE, CONDUIT, POLISHED_GRANITE_STAIRS, SMOOTH_RED_SANDSTONE_STAIRS, MOSSY_STONE_BRICK_STAIRS, POLISHED_DIORITE_STAIRS, MOSSY_COBBLESTONE_STAIRS, END_STONE_BRICK_STAIRS, STONE_STAIRS, SMOOTH_SANDSTONE_STAIRS, SMOOTH_QUARTZ_STAIRS, GRANITE_STAIRS, ANDESITE_STAIRS, RED_NETHER_BRICK_STAIRS, POLISHED_ANDESITE_STAIRS, DIORITE_STAIRS, COBBLED_DEEPSLATE_STAIRS, POLISHED_DEEPSLATE_STAIRS, DEEPSLATE_BRICK_STAIRS, DEEPSLATE_TILE_STAIRS, POLISHED_GRANITE_SLAB, SMOOTH_RED_SANDSTONE_SLAB, MOSSY_STONE_BRICK_SLAB, POLISHED_DIORITE_SLAB, MOSSY_COBBLESTONE_SLAB, END_STONE_BRICK_SLAB, SMOOTH_SANDSTONE_SLAB, SMOOTH_QUARTZ_SLAB, GRANITE_SLAB, ANDESITE_SLAB, RED_NETHER_BRICK_SLAB, POLISHED_ANDESITE_SLAB, DIORITE_SLAB, COBBLED_DEEPSLATE_SLAB, POLISHED_DEEPSLATE_SLAB, DEEPSLATE_BRICK_SLAB, DEEPSLATE_TILE_SLAB, SCAFFOLDING, REDSTONE, REDSTONE_TORCH, REDSTONE_BLOCK, REPEATER, COMPARATOR, PISTON, STICKY_PISTON, SLIME_BLOCK, HONEY_BLOCK, OBSERVER, HOPPER, DISPENSER, DROPPER, LECTERN, TARGET, LEVER, LIGHTNING_ROD, DAYLIGHT_DETECTOR, TRIPWIRE_HOOK, TRAPPED_CHEST, TNT, REDSTONE_LAMP, NOTE_BLOCK, STONE_BUTTON, POLISHED_BLACKSTONE_BUTTON, OAK_BUTTON, SPRUCE_BUTTON, BIRCH_BUTTON, JUNGLE_BUTTON, ACACIA_BUTTON, DARK_OAK_BUTTON, MANGROVE_BUTTON, CRIMSON_BUTTON, WARPED_BUTTON, STONE_PRESSURE_PLATE, POLISHED_BLACKSTONE_PRESSURE_PLATE, LIGHT_WEIGHTED_PRESSURE_PLATE, HEAVY_WEIGHTED_PRESSURE_PLATE, OAK_PRESSURE_PLATE, SPRUCE_PRESSURE_PLATE, BIRCH_PRESSURE_PLATE, JUNGLE_PRESSURE_PLATE, ACACIA_PRESSURE_PLATE, DARK_OAK_PRESSURE_PLATE, MANGROVE_PRESSURE_PLATE, CRIMSON_PRESSURE_PLATE, WARPED_PRESSURE_PLATE, IRON_DOOR, OAK_DOOR, SPRUCE_DOOR, BIRCH_DOOR, JUNGLE_DOOR, ACACIA_DOOR, DARK_OAK_DOOR, MANGROVE_DOOR, CRIMSON_DOOR, WARPED_DOOR, IRON_TRAPDOOR, OAK_TRAPDOOR, SPRUCE_TRAPDOOR, BIRCH_TRAPDOOR, JUNGLE_TRAPDOOR, ACACIA_TRAPDOOR, DARK_OAK_TRAPDOOR, MANGROVE_TRAPDOOR, CRIMSON_TRAPDOOR, WARPED_TRAPDOOR, OAK_FENCE_GATE, SPRUCE_FENCE_GATE, BIRCH_FENCE_GATE, JUNGLE_FENCE_GATE, ACACIA_FENCE_GATE, DARK_OAK_FENCE_GATE, MANGROVE_FENCE_GATE, CRIMSON_FENCE_GATE, WARPED_FENCE_GATE, POWERED_RAIL, DETECTOR_RAIL, RAIL, ACTIVATOR_RAIL, MINECART, CHEST_MINECART, FURNACE_MINECART, TNT_MINECART, HOPPER_MINECART, CARROT_ON_A_STICK, WARPED_FUNGUS_ON_A_STICK, OAK_BOAT, OAK_CHEST_BOAT, SPRUCE_BOAT, SPRUCE_CHEST_BOAT, BIRCH_BOAT, BIRCH_CHEST_BOAT, JUNGLE_BOAT, JUNGLE_CHEST_BOAT, ACACIA_BOAT, ACACIA_CHEST_BOAT, DARK_OAK_BOAT, DARK_OAK_CHEST_BOAT, MANGROVE_BOAT, MANGROVE_CHEST_BOAT, TURTLE_HELMET, FLINT_AND_STEEL, BOW, ARROW, COAL, DIAMOND, EMERALD, LAPIS_LAZULI, RAW_IRON, IRON_INGOT, RAW_COPPER, COPPER_INGOT, RAW_GOLD, GOLD_INGOT, NETHERITE_INGOT, WOODEN_SWORD, WOODEN_SHOVEL, WOODEN_PICKAXE, WOODEN_AXE, WOODEN_HOE, STONE_SWORD, STONE_SHOVEL, STONE_PICKAXE, STONE_AXE, STONE_HOE, GOLDEN_SWORD, GOLDEN_SHOVEL, GOLDEN_PICKAXE, GOLDEN_AXE, GOLDEN_HOE, IRON_SWORD, IRON_SHOVEL, IRON_PICKAXE, IRON_AXE, IRON_HOE, DIAMOND_SWORD, DIAMOND_SHOVEL, DIAMOND_PICKAXE, DIAMOND_AXE, DIAMOND_HOE, STICK, BOWL, MUSHROOM_STEW, WHEAT, BREAD, LEATHER_HELMET, LEATHER_CHESTPLATE, LEATHER_LEGGINGS, LEATHER_BOOTS, IRON_HELMET, IRON_CHESTPLATE, IRON_LEGGINGS, IRON_BOOTS, DIAMOND_HELMET, DIAMOND_CHESTPLATE, DIAMOND_LEGGINGS, DIAMOND_BOOTS, GOLDEN_HELMET, GOLDEN_CHESTPLATE, GOLDEN_LEGGINGS, GOLDEN_BOOTS, PAINTING, GOLDEN_APPLE, OAK_SIGN, SPRUCE_SIGN, BIRCH_SIGN, JUNGLE_SIGN, ACACIA_SIGN, DARK_OAK_SIGN, MANGROVE_SIGN, CRIMSON_SIGN, WARPED_SIGN, BUCKET, LEATHER, DRIED_KELP_BLOCK, PAPER, BOOK, SLIME_BALL, COMPASS, RECOVERY_COMPASS, FISHING_ROD, CLOCK, SPYGLASS, WHITE_DYE, ORANGE_DYE, MAGENTA_DYE, LIGHT_BLUE_DYE, YELLOW_DYE, LIME_DYE, PINK_DYE, GRAY_DYE, LIGHT_GRAY_DYE, CYAN_DYE, PURPLE_DYE, BLUE_DYE, BROWN_DYE, RED_DYE, BLACK_DYE, BONE_MEAL, SUGAR, CAKE, WHITE_BED, ORANGE_BED, MAGENTA_BED, LIGHT_BLUE_BED, YELLOW_BED, LIME_BED, PINK_BED, GRAY_BED, LIGHT_GRAY_BED, CYAN_BED, PURPLE_BED, BLUE_BED, BROWN_BED, GREEN_BED, RED_BED, BLACK_BED, COOKIE, SHEARS, DRIED_KELP, PUMPKIN_SEEDS, MELON_SEEDS, GOLD_NUGGET, GLASS_BOTTLE, FERMENTED_SPIDER_EYE, BLAZE_POWDER, MAGMA_CREAM, BREWING_STAND, CAULDRON, ENDER_EYE, GLISTERING_MELON_SLICE, FIRE_CHARGE, WRITABLE_BOOK, ITEM_FRAME, GLOW_ITEM_FRAME, FLOWER_POT, MAP, GOLDEN_CARROT, PUMPKIN_PIE, FIREWORK_ROCKET, RABBIT_STEW, ARMOR_STAND, LEATHER_HORSE_ARMOR, LEAD, WHITE_BANNER, ORANGE_BANNER, MAGENTA_BANNER, LIGHT_BLUE_BANNER, YELLOW_BANNER, LIME_BANNER, PINK_BANNER, GRAY_BANNER, LIGHT_GRAY_BANNER, CYAN_BANNER, PURPLE_BANNER, BLUE_BANNER, BROWN_BANNER, GREEN_BANNER, RED_BANNER, BLACK_BANNER, END_CRYSTAL, BEETROOT_SOUP, SPECTRAL_ARROW, SHIELD, IRON_NUGGET, MUSIC_DISC_5, CROSSBOW, LOOM, FLOWER_BANNER_PATTERN, CREEPER_BANNER_PATTERN, SKULL_BANNER_PATTERN, MOJANG_BANNER_PATTERN, COMPOSTER, BARREL, SMOKER, BLAST_FURNACE, CARTOGRAPHY_TABLE, FLETCHING_TABLE, GRINDSTONE, SMITHING_TABLE, STONECUTTER, LANTERN, SOUL_LANTERN, CAMPFIRE, SOUL_CAMPFIRE, BEEHIVE, HONEY_BOTTLE, HONEYCOMB_BLOCK, LODESTONE, BLACKSTONE_SLAB, BLACKSTONE_STAIRS, POLISHED_BLACKSTONE, POLISHED_BLACKSTONE_SLAB, POLISHED_BLACKSTONE_STAIRS, CHISELED_POLISHED_BLACKSTONE, POLISHED_BLACKSTONE_BRICKS, POLISHED_BLACKSTONE_BRICK_SLAB, POLISHED_BLACKSTONE_BRICK_STAIRS, RESPAWN_ANCHOR, CANDLE, WHITE_CANDLE, ORANGE_CANDLE, MAGENTA_CANDLE, LIGHT_BLUE_CANDLE, YELLOW_CANDLE, LIME_CANDLE, PINK_CANDLE, GRAY_CANDLE, LIGHT_GRAY_CANDLE, CYAN_CANDLE, PURPLE_CANDLE, BLUE_CANDLE, BROWN_CANDLE, GREEN_CANDLE, RED_CANDLE, BLACK_CANDLE ->
                    true;
            default -> false;
        };
    }

}
